# Generated by Django 5.2.5 on 2025-08-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
    ]
