# Generated by Django 5.2.5 on 2025-09-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_itemcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcomment',
            old_name='name',
            new_name='item',
        ),
    ]
